name: Build and Deploy Snapshot
on:
  push:
    branches:
      - main
permissions:
  actions: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  build-and-deploy-snapshot:
    if: ${{ github.repository == 'spring-projects/spring-retry' }}
    name: Build and Deploy Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Build and Publish
        id: build-and-publish
        uses: ./.github/actions/build
        with:
          publish: true
      - name: Deploy
        uses: spring-io/artifactory-deploy-action@26bbe925a75f4f863e1e529e85be2d0093cac116 # v0.0.1
        with:
          uri: 'https://repo.spring.io'
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          build-name: 'spring-retry-2.0.x'
          repository: 'libs-snapshot-local'
          folder: 'deployment-repository'
          signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
          signing-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          artifact-properties: |
            /**/*.zip::zip.name=${{ github.event.repository.name }},zip.deployed=false
            /**/*docs.zip::zip.type=docs
      - name: Send Notification
        uses: ./.github/actions/send-notification
        if: always()
        with:
          webhook-url: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          status: ${{ job.status }}
          run-name: ${{ format('{0} | Linux | Java 17', github.ref_name) }}
    outputs:
      version: ${{ steps.build-and-publish.outputs.version }}
